import type { Metadata } from "next";
import { StoreProvider } from "./StoreProvider";

export const metadata: Metadata = {
  title: "Frontend Repository - Ebuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
